export const packages = [
  {
    id: "akrab-super-big-lite",
    name: "AKRAB SUPER BIG LITE",
    price: 40000,
    areas: [
      { area: 1, quota: "7,5 GB" },
      { area: 2, quota: "12 GB" },
      { area: 3, quota: "25 GB" },
      { area: 4, quota: "65 GB" },
    ],
    hasBonus: false,
    isPromo: true,
    noWarranty: true,
  },
  {
    id: "akrab-super-big-rw",
    name: "AKRAB SUPER BIG RW",
    price: 45000,
    areas: [
      { area: 1, quota: "25 GB" },
      { area: 2, quota: "30 GB" },
      { area: 3, quota: "43 GB" },
      { area: 4, quota: "83 GB" },
    ],
    hasBonus: false,
    isPromo: true,
    noWarranty: true,
  },
  {
    id: "akrab-super-mini",
    name: "AKRAB SUPER MINI",
    price: 53000,
    areas: [
      { area: 1, quota: "13 - 15 GB" },
      { area: 2, quota: "15 - 17 GB" },
      { area: 3, quota: "20 - 22 GB" },
      { area: 4, quota: "30 - 37 GB" },
    ],
    hasBonus: true,
  },
  {
    id: "akrab-super-mini-plus",
    name: "AKRAB SUPER MINI PLUS",
    price: 56000,
    areas: [
      { area: 1, quota: "15,5 GB" },
      { area: 2, quota: "18,5 GB" },
      { area: 3, quota: "29 GB" },
      { area: 4, quota: "53 GB" },
    ],
    hasBonus: true,
  },
  {
    id: "akrab-mini",
    name: "AKRAB MINI",
    price: 65000,
    areas: [
      { area: 1, quota: "31 - 33 GB" },
      { area: 2, quota: "33 - 35 GB" },
      { area: 3, quota: "38 - 40 GB" },
      { area: 4, quota: "48 - 50 GB" },
    ],
    hasBonus: true,
  },
  {
    id: "akrab-super-big",
    name: "AKRAB SUPER BIG",
    price: 65000,
    areas: [
      { area: 1, quota: "25 - 27 GB" },
      { area: 2, quota: "30 - 32 GB" },
      { area: 3, quota: "43 - 45 GB" },
      { area: 4, quota: "83 - 85 GB" },
    ],
    hasBonus: true,
    isPromo: true,
  },
  {
    id: "akrab-big",
    name: "AKRAB BIG",
    price: 67000,
    areas: [
      { area: 1, quota: "38 - 40 GB" },
      { area: 2, quota: "40 - 42 GB" },
      { area: 3, quota: "45 - 47 GB" },
      { area: 4, quota: "55 - 57 GB" },
    ],
    hasBonus: true,
  },
  {
    id: "akrab-jumbo-lite",
    name: "AKRAB JUMBO LITE",
    price: 75000,
    areas: [
      { area: 1, quota: "50,5 - 52,5 GB" },
      { area: 2, quota: "52,5 - 54,5 GB" },
      { area: 3, quota: "57,5 - 59,5 GB" },
      { area: 4, quota: "67,5 - 69,5 GB" },
    ],
    hasBonus: true,
  },
  {
    id: "akrab-jumbo",
    name: "AKRAB JUMBO",
    price: 85000,
    areas: [
      { area: 1, quota: "65 GB" },
      { area: 2, quota: "70 GB" },
      { area: 3, quota: "83 GB" },
      { area: 4, quota: "123 GB" },
    ],
    hasBonus: true,
  },
  {
    id: "akrab-mega-big",
    name: "AKRAB MEGA BIG",
    price: 99000,
    areas: [
      { area: 1, quota: "88 - 90 GB" },
      { area: 2, quota: "90 - 92 GB" },
      { area: 3, quota: "95 - 97 GB" },
      { area: 4, quota: "105 - 107 GB" },
    ],
    hasBonus: true,
    isPromo: true,
  },
  {
    id: "bebas-puas-90-105",
    name: "BEBAS PUAS 90 - 105 GB",
    price: 95000,
    areas: [
      { area: 1, quota: "90 - 105 GB" },
      { area: 2, quota: "90 - 105 GB" },
      { area: 3, quota: "90 - 105 GB" },
      { area: 4, quota: "90 - 105 GB" },
    ],
    hasBonus: true,
    isPromo: true,
  },
  {
    id: "bebas-puas-234-285",
    name: "BEBAS PUAS 234 - 285 GB",
    price: 155000,
    areas: [
      { area: 1, quota: "234 - 285 GB" },
      { area: 2, quota: "234 - 285 GB" },
      { area: 3, quota: "234 - 285 GB" },
      { area: 4, quota: "234 - 285 GB" },
    ],
    hasBonus: true,
    isPromo: true,
  },
]
